management:
    info:
      env:
        enabled: true

    application:
        name: Blog bakcend application
        description: A blog with articles about The about anything.
        author: Adrian Nare
        version: '@project.version@'

app:
    property:
      signupUrl: ${SIGN_UP_URL}
      authKey: ${AUTH_KEY}
      headerName: ${HEADER_NAME}
      expirationTime: ${EXPIRATION_TIME}

spring:
  profiles:
    active: dev
