spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    username: postgres
    password: 12345678
    platform: postgres
    data: classpath:/sql/import.sql
    # initialization for spring-boot before 2.5, change to other value once values have been loaded
    initialization-mode: never
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      # change to update when the tables have been created in database
      ddl-auto: update

  # initialization for spring-boot after 2.5
  #sql:
  #  init:
  #    mode: always

# logging the spring security filter chain
#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG


