spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    platform: postgres
    data: classpath:/sql/import.sql
    # initialization for spring-boot before 2.5, change to other value once values have been loaded
    initialization-mode: never

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update
  # initialization for spring-boot after 2.5
  #sql:
  #  init:
  #    mode: always
