spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PART}/${PROD_DB_NAME}
    username: postgres
    password: 12345678
    platform: postgres
    data: classpath:/sql/import.sql

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always


